name = "GeoStatsPlots"
uuid = "cf22561b-6452-4701-9483-6c69015d00e1"
authors = ["Elias Carvalho <eliascarvdev@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshPlots = "de9684d3-f81f-49d9-ae9e-c828b202dea9"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[compat]
Distances = "0.10"
GeoStatsBase = "0.28"
MeshPlots = "0.1"
Meshes = "0.24, 0.25"
RecipesBase = "1"
Variography = "0.15"
julia = "1.6"
